name: AutoCoder Workflow

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot') # Check for the label at the job level

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token secret
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPOSITORY: ${{ github.repository }}  # The full repository name
          ISSUE_NUMBER: ${{ github.event.issue.number }}  # The issue number
        run: |
          chmod +x ./scripts/script.sh
          ./scripts/script.sh "${GITHUB_TOKEN}" "${REPOSITORY}" "${ISSUE_NUMBER}" "${OPENAI_API_KEY}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: List Generated Code Files
        run: |
          echo "Listing files in the autocoder-artifact directory:"
          ls -R autocoder-artifact/