name: AutoCoder Workflow

on:
  issues:
    types: [opened, reopened]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot') # Check for the label at the job level

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Issue Information
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
        run: |
          echo "Issue Number: ${ISSUE_NUMBER}"
          echo "Issue Title: ${ISSUE_TITLE}"
          echo "Issue Body: ${ISSUE_BODY}"
          echo "Issue Assignees: ${ISSUE_ASSIGNEES}"
          echo "Issue Labels: ${ISSUE_LABELS}"

      - name: Generate Code with ChatGPT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token secret
          OPENAI_API_KEY: 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
          REPOSITORY: ${{ github.repository }}  # The full repository name
          ISSUE_NUMBER: ${{ github.event.issue.number }}  # The issue number
        run: |
          chmod +x ./scripts/script.sh
          ./scripts/script.sh "${GITHUB_TOKEN}" "${REPOSITORY}" "${ISSUE_NUMBER}" "${OPENAI_API_KEY}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: List Generated Code Files
        run: |
          echo "Listing files in the autocoder-artifact directory:"
          ls -R autocoder-artifact/