name: AutoCoder Workflow

on:
  push:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout

      - name: Greeting message
        run: echo "Hello, world"